# Numpy

Hoje, vamos começara ver a biblioteca matemática mais importante pro ecossistema 
científico do Python: O Numpy.

Vamos relembrar alguns conceitos

In [105]:
lista = ["a", 2, 2.4, True, [1, 3], {"a": 1}]
lista

['a', 2, 2.4, True, [1, 3], {'a': 1}]

In [106]:
lista.append("Olá")

In [107]:
lista

['a', 2, 2.4, True, [1, 3], {'a': 1}, 'Olá']

In [108]:
a = 42.5

In [109]:
a = 'aaaaa'

In [110]:
a

'aaaaa'

A biblioteca **NumPy** _(Numerical Python)_ proporciona uma forma eficiente de armazenagem e processamento de conjuntos de dados, e é utilizada como base para a construção da biblioteca Pandas, que estudaremos a seguir.

O diferencial do Numpy é sua velocidade e eficiência, o que faz com que ela seja amplamente utilizada para computação científica e analise de dados. 

A velocidade e eficiência é possível graças à estrutura chamada **numpy array**, que é um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.
Link da Documentação: https://numpy.org/doc/

In [112]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [113]:
# A gente importa o numpy sempre chamando ele de "np"
import numpy as np

In [116]:
# Vamos fazer uma comparação com uma lista de Python
py_array = [[1, 2, 3]]

print(py_array)
print(type(py_array))

[[1, 2, 3]]
<class 'list'>


In [117]:
# Uma lista com 2 dimensões é uma lista de listas
print(type(py_array[0]))

<class 'list'>


In [118]:
# Nota como o tipo da variável muda para "ndarray"
np_array = np.array(py_array)

print(np_array)
print(type(np_array))
print(np_array.dtype)

[[1 2 3]]
<class 'numpy.ndarray'>
int32


In [136]:
py_array_string = [['a', 1, 3]]
np_array_string = np.array(py_array_string)

print(np_array_string)
print(type(np_array_string))
print(np_array_string.dtype)

[['a' '1' '3']]
<class 'numpy.ndarray'>
<U11


In [142]:
py_array_string = [['a', 2, 3, 2.4, "@@#!SD"]]
np_array_string = np.array(py_array_string)

print(np_array_string)
print(type(np_array_string))
print(np_array_string.dtype)

[['a' '2' '3' '2.4' '@@#!SD']]
<class 'numpy.ndarray'>
<U32


In [143]:
np_array_string

array([['a', '2', '3', '2.4', '@@#!SD']], dtype='<U32')

In [148]:
np_array_string[0][0]

'a'

In [131]:
# Mas no  numpy, um ndarray continua sendo formado de ndarrays.
print(type(np_array_string[0]))

<class 'numpy.ndarray'>


In [151]:
np_array

array([[1, 2, 3]])

In [150]:
np_array_string

array([['a', '2', '3', '2.4', '@@#!SD']], dtype='<U32')

In [152]:
# 3 atributos básicos pra um ndarray
print(np_array.shape) # o formato do array
print(np_array.ndim)  # quantidade de dimensões
print(np_array.dtype) # o tipo de dado dos elementos do array

(1, 3)
2
int32


In [153]:
# 3 atributos básicos pra um ndarray
print(np_array_string.shape) # o formato do array
print(np_array_string.ndim)  # quantidade de dimensões
print(np_array_string.dtype) # o tipo de dado dos elementos do array

(1, 5)
2
<U32


In [154]:
# Diferença entre o tipo array e o tipo de dado dentro do array
print(type(np_array))
print(np_array.dtype)

<class 'numpy.ndarray'>
int32


In [155]:
# O dtype de um array do numpy pode ser controlado na hora que a gente cria.
py_array = [1, 2, 3]

array_int = np.array(py_array, dtype=np.float64)

In [157]:
lista_exemplo = [1, 2, 3]
print(float(lista_exemplo[0]))

1.0


In [156]:
print(array_int)
print(array_int.dtype)

[1. 2. 3.]
float64


In [158]:
array_int_2 = np.array([1, 2, 3], np.float64)

In [159]:
print(array_int_2)
print(array_int_2.dtype)

[1. 2. 3.]
float64


In [165]:
# Mas quando a gente não define, ele infere a partir dos nossos dados.
py_array_2 = [1.0, 2, 3]

array_float = np.array(py_array_2)

print(array_float)
print(array_float.dtype)

[1. 2. 3.]
float64


In [163]:
# Para selecionar um elemento de uma tabela no Python e no Numpy, tem uma ligeira diferença.
print(array_float[2])

3.0


**Revisando**

In [166]:
# No Python, existe o conceito de "indexing", que é pegar elementos pelo seu índice (a sua posição)
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9] 
print(lista[0])
print(lista[3])
print(lista[-1])
print(lista[-3])
print(lista[-9])

# Obs.: Lembre-se que as posições no python sempre começam a contar do zero!

1
4
9
7
1


In [167]:
print(lista[0]==lista[-9])

True


In [169]:
# Também existe uma forma de pegar um subconjunto da lista.
# A gente chama isso de "slicing". Nota que o último elemento não entra!
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9] 
print(lista[:])
print(lista[2:3])
print(lista[2:-3])

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[3]
[3, 4, 5, 6]


In [170]:
# Podemos definir um início também pro slicing.
# Quando não colocamos nada, ele assume que o início é 0.
# No caso do fim, se não colocamos nada, ele assume que o fim é o último elemento.
print(lista[:-3])
print(lista[-3:])

[1, 2, 3, 4, 5, 6]
[7, 8, 9]


In [175]:
# O poder do slicing é que a gente pode definir diferentes tamanhos de passo.
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9] 
print(lista[0:9:2])
print(lista[1:5:-1])
print(lista[-1:5:-1])

[1, 3, 5, 7, 9]
[]
[9, 8, 7]


In [177]:
# Inverter essa lista
print(lista[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1]


Também podemos aplicar o conceito do slicing no numpy

In [178]:
# O dtype de um array do numpy pode ser controlado na hora que a gente cria.
py_array = [1, 2, 3]

array_int = np.array(py_array, dtype=np.float64)

In [179]:
print(array_int)
print(array_int[2])
print(array_int[:1])
print(array_int[-1:-5:-2])

[1. 2. 3.]
3.0
[1.]
[3. 1.]


**Funções numpy**  
O numpy também tem diversas funções para facilitar criação de arrays.

In [180]:
print(np.zeros(10))
print(np.ones(5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [181]:
# Alguns spoilers
print(np.identity(4))
print(np.eye(4, 3))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [182]:
# Relembrando a função range
list(range(2, 10, 2))

[2, 4, 6, 8]

In [183]:
# Também podemos fazer listas de números.
print(np.arange(2, 10, 2))
print(np.arange(10.5, 30.5, 5))

[2 4 6 8]
[10.5 15.5 20.5 25.5]


In [204]:
print(np.linspace(0, 50, 50, retstep=False))

[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]


# Operações Básicas

In [212]:
# Se a força do numpy é ter tudo operando como vetores, 
# então ele tem que ter operações de vetores.
vetor1 = np.arange(0, 10)
vetor2 = np.arange(0, 20, 2)

print(vetor1)
print(vetor2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [213]:
# Soma por elemento
print(vetor1 + vetor2)

[ 0  3  6  9 12 15 18 21 24 27]


In [214]:
# Multiplicação elemento por elemento
print(vetor1 * vetor2)

[  0   2   8  18  32  50  72  98 128 162]


In [217]:
print((vetor1 * vetor2).sum())

570


In [215]:
# produto de matrizes (neste caso, produto escalar)
# Isso é multiplicar elemento por elemento, e depois somar
print((vetor1 * vetor2).sum())
print(vetor1 @ vetor2)

570
570


## Bora praticar!

1) Inverta um vetor (o primeiro elemento vira o último). Para testar crie um vetor a partir da seguinte lista [0, 5, 1, 9, 9, 87]

In [218]:
lista = [0, 5, 1, 9, 9, 87]
np_array = np.array(lista)
print(np_array[::-1])

[87  9  9  1  5  0]


In [219]:
print(np.flip(lista))

[87  9  9  1  5  0]


In [220]:
lista = [0, 5, 1, 9, 9, 87]
print(np.array(lista[::-1]))

[87  9  9  1  5  0]


2) Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [225]:
vetor_1 = np.arange(1, 22, 2)
print(vetor_1)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [226]:
print(np.arange(1, 22, 2))

[ 1  3  5  7  9 11 13 15 17 19 21]


In [232]:
array_1 = np.arange(1, 22, 0.5)
print(array_1)
print(array_1[::2])
print(array_1[::2][::2])

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21.]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]


3) Ache os índices dos elementos não-zero a partir do array [1,2,0,0,4,0]

In [233]:
vetor = np.array([1, 2, 0, 0, 4,0])
indices = [i for i in range(len(vetor)) if vetor[i] != 0]
print(indices)

[0, 1, 4]


In [243]:
np.nonzero(vetor)[0]

array([0, 1, 4], dtype=int64)

In [238]:
np.flatnonzero(vetor)

array([0, 1, 4], dtype=int64)

In [244]:
# Criar um array de exemplo
arr = np.array([0, 1, 2, 1, 0, 3, 1, 4])

# Encontrar os índices dos elementos iguais a 1
indices = np.where(arr == 1)

print(indices)  # (array([1, 3, 6]),)

(array([1, 3, 6], dtype=int64),)


E se a gente quisesse pegar os elementos diferentes de zero?

In [252]:
vetor = np.array([1, 2, 0, 0, 4,0])
valores = [valor for valor in vetor if valor != 0]
print(valores)

[1, 2, 4]


In [251]:
vetor = np.array([1, 2, 0, 0, 4,0])
print(vetor[vetor !=0])

[1 2 4]


4) Crie uma matriz identidade 3x3

In [253]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

5) Crie um array de 10 com valores aleatórios 

In [3]:
import numpy as np
np.random.rand(10)

array([0.30937048, 0.49192902, 0.01319193, 0.18736564, 0.86009729,
       0.5759267 , 0.69953442, 0.40371294, 0.40036979, 0.4457492 ])

In [7]:
import random 

lista = []

for i in range(10):
    numero_aleatorio = random.randrange(0, 100)
    lista.append(numero_aleatorio)
print(np.array(lista))

[99 92 93 27 69 63 13 63  0 93]


In [8]:
import random 

lista = []

for i in range(10):
    numero_aleatorio = random.random()
    lista.append(numero_aleatorio)
print(np.array(lista))

[0.32807531 0.66234595 0.67498464 0.89514341 0.29968616 0.56428069
 0.6248913  0.22610426 0.08723716 0.91335015]


6) Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [15]:
aleatorios = np.random.random(100)
print(max(aleatorios), min(aleatorios))

0.9866765127486671 0.044209876581698504


In [42]:
array_2 = np.random.randint(0, 1000, size=100)
print(np.max(array_2), np.min(array_2))

18 1


In [46]:
d20 = np.random.randint(0,20,size=1)
print(d20)

[8]


7) Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [49]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
linhas = 5
colunas = 5

array_2d = np.ones((linhas, colunas), dtype=int)
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [58]:
dim = 5

array = [[0 for _ in range(dim)] for _ in range(dim)]
print(array)
for i in range(dim):
    for j in range(dim):
        if i == 0 or i == dim - 1 or j == 0 or j == dim - 1:
            array[i][j] = 1

for linha in array:
    print(linha)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
[1, 1, 1, 1, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 1, 1, 1, 1]


In [ ]:
colunas = 3
linhas = 3

array2d = []
for i in range(linhas):
    linha = []
    for j in range(colunas):
        if i == 0 or i == linhas-1 or j == 0 or j == colunas-1:
            linha.append(1)
        else:
            linha.append(0)
    array2d.append(linha)


for linha in array2d:
    print(linha)

8) Crie uma matriz 5x5 com valores 1, 2, 3, 4 logo abaixo da diagonal

In [61]:
np.eye(10, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [63]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [70]:
matriz = np.zeros((5, 5))

for i in range(1, 5):
    matriz[i, i - 1] = i 

print(matriz)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


## Mini tarefa

Utilizando o numpy crie dois vetores a partir das listas ```lista_1 = [1, 2, 3, 4]``` e ```lista_2 = [12, 6, 0, 29]``` e calcule o produto escalar entre esses dois vetores.

In [103]:

# O produto escalar é uma operação matemática entre dois vetores que resulta em um único número (escalar). 
# Para calcular, você multiplica os elementos correspondentes dos dois vetores e soma os resultados. 
# Ele mede a "projeção" de um vetor no outro, ou seja, o quanto eles estão "alinhados"na mesma direção. 
# Se o produto escalar for 0, significa que os vetores são perpendiculares (não têm nenhuma projeção um no outro).

In [72]:
lista_1 = [1, 2, 3, 4]

lista_2 = [12, 6, 0, 29]

produtoEscalar = np.dot(lista_1, lista_2)

print(produtoEscalar)

140


In [73]:
lista_1 = np.arange(1,5)
lista_2 = [12, 6, 0, 29]

print(lista_1)
print(lista_2)
print((lista_1 * lista_2).sum())
print(lista_1 @ lista_2)

[1 2 3 4]
[12, 6, 0, 29]
140
140


In [76]:
lista_1 = np.array([1, 2, 3, 4])

lista_2 = np.array([12, 6, 0, 29])
print(lista_1 * lista_2)
print((lista_1 * lista_2).sum())

[ 12  12   0 116]
140
