# Numpy

**Relembrando**  
  
A biblioteca **NumPy** _(Numerical Python)_ proporciona uma forma eficiente de armazenagem e processamento de conjuntos de dados, e é utilizada como base para a construção da biblioteca Pandas, que estudaremos a seguir.

O diferencial do Numpy é sua velocidade e eficiência, o que faz com que ela seja amplamente utilizada para computação científica e analise de dados. 

A velocidade e eficiência é possível graças à estrutura chamada **numpy array**, que é um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

In [2]:
# A gente importa o numpy sempre chamando ele de "np"
import numpy as np

In [11]:
py_array = [1, 2, 3]

np_array = np.array(py_array)

print(np_array)
print(type(np_array))

[1 2 3]
<class 'numpy.ndarray'>


In [12]:
print(type(np_array[0]))

<class 'numpy.int32'>


In [13]:
# Vamos fazer uma comparação com um vetor do numpy
py_matriz = [[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9],
             [10, 11, 12]]

np_matriz = np.array(py_matriz)

print(np_matriz)
print(type(np_matriz))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


In [20]:
np_matriz[0]

array([1, 2, 3])

In [21]:
print(type(np_matriz[0]))

<class 'numpy.ndarray'>


In [24]:
np_matriz[0,0]

1

In [25]:
np_matriz[0][0]

1

In [26]:
# 3 atributos básicos pra um ndarray
print(np_matriz.shape) # O formato da matriz
print(np_matriz.ndim)  # Quantidade de dimensões
print(np_matriz.dtype) # Tipo de dado dos elementos da matriz

(4, 3)
2
int32


In [27]:
x = np.array([1, 2, 3])
print(type(x))
print(x.dtype)

<class 'numpy.ndarray'>
int32


In [28]:
# O dtype de um array do numpy pode ser controlado na hora que a gente cria.
py_matriz = [[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9],
             [10, 11, 12]]

matriz = np.array(py_matriz, dtype=np.float64)

In [29]:
print(matriz)
print(matriz.dtype)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
float64


In [30]:
# Para selecionar um elemento de uma tabela no Python e no Numpy, tem uma ligeira diferença.
print(matriz[0][0])
print(matriz[0, 0])

1.0
1.0


Slicing com matriz

In [31]:
y = np.array([1, 2, 3, 4, 5, 6, 7])
print(y)

[1 2 3 4 5 6 7]


In [65]:
print(y[1:-1])
print('')
print(y[::2])
print('')
print(y[-1:])

[2 3 4 5 6]

[1 3 5 7]

[7]


In [39]:
matriz[1]

array([4., 5., 6.])

In [48]:
# Slicing funciona no numpy!
print(matriz)
print('')
print(matriz[:,2:])
print('')
print(matriz[1:,:])
print('')
print(matriz[1,::-1])
print('')
print(matriz[1:-1,-1:])

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]

[[ 3.]
 [ 6.]
 [ 9.]
 [12.]]

[[ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]

[6. 5. 4.]

[[6.]
 [9.]]


In [49]:
print(matriz)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [52]:
print(matriz[1:3,:])

[[4. 5. 6.]
 [7. 8. 9.]]


In [72]:
print(matriz[1:-1,-1:])

[[6.]
 [9.]]


**Funções numpy**  
O numpy também tem diversas funções para facilitar criação de matrizes.

In [73]:
print(np.zeros((2, 3)))
print(np.ones((3, 2)))
print(np.identity(3))
print(np.eye(4, 3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# Manipulações de matrizes

In [74]:
matriz

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [75]:
# Transposição de matrizes
matriz.T

array([[ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  6.,  9., 12.]])

In [76]:
np.transpose(matriz)

array([[ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  6.,  9., 12.]])

In [77]:
matriz.transpose()

array([[ 1.,  4.,  7., 10.],
       [ 2.,  5.,  8., 11.],
       [ 3.,  6.,  9., 12.]])

In [78]:
x = np.array([0.1, 0.4, 1.0, 0.2, 0.7, 1.2, 1.1, 1.0, 0.9])
x.shape

(9,)

In [81]:
# Redimensionamento
x.reshape(3, 3)

array([[0.1, 0.4, 1. ],
       [0.2, 0.7, 1.2],
       [1.1, 1. , 0.9]])

In [83]:
y = np.array([0.1, 0.4, 1.0, 0.2, 0.7, 1.2, 1.1, 1.0, 0.9, 2.0,
              1.5, 1.6])
y.shape

(12,)

In [84]:
# Vejam o que acontece se as dimensões não são condizentes
y.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [85]:
y.reshape(4, 3)

array([[0.1, 0.4, 1. ],
       [0.2, 0.7, 1.2],
       [1.1, 1. , 0.9],
       [2. , 1.5, 1.6]])

In [86]:
y.reshape(4, 3).shape

(4, 3)

In [94]:
# E se eu quiser retornar para um vetor
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
x.reshape(-1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [95]:
# Também é possível utilizar o flatten
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
# Também podemos combinar arrays diferentes.
# Imagina que temos duas features, altura e peso de pessoas físicas.
x1 = np.array([[1.67, 89.],
               [1.79, 85.],
               [1.69, 65.],
               [1.54, 57.],
               [1.50, 45.]])

# Porém, nós queremos testar agora adicionar uma terceira feature, se a pessoa é homem ou mulher.
# 1 é mulher, 0 é homem
x2 = np.array([1, 0, 1, 0, 1])

# Como podemos fazer?

In [105]:
x2.shape

(5,)

In [106]:
x2 = x2.reshape(-1, 1)
print(x2)

[[1]
 [0]
 [1]
 [0]
 [1]]


In [107]:
x2.shape

(5, 1)

In [109]:
# Podemos utilizar o concatenate
np.concatenate((x1, x2), axis=1)

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [108]:
# Podemos utilizar o concatenate
np.concatenate((x1, x2.reshape(-1, 1)), axis=1)

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [111]:
x1.shape

(5, 2)

In [112]:
x2.shape

(5, 1)

In [115]:
x2.T

array([[1, 0, 1, 0, 1]])

In [114]:
x2.T.shape

(1, 5)

In [110]:
np.concatenate((x1, x2.T), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 1

O erro ocorre porque a função `np.concatenate()` exige que todos os arrays fornecidos como entrada tenham o mesmo número de dimensões. No seu código, o array `x1` tem 2 dimensões, mas o array `x2.T` (após a transposição) tem 1 dimensão.

### Análise detalhada:

- **`x1`**: Esse array tem 2 dimensões (provavelmente uma matriz ou uma tabela).
- **`x2`**: Esse array parece ser 1D (um vetor). Após a transposição (`x2.T`), ele permanece 1D porque a transposição de um array 1D não altera sua forma.
  
- **`np.concatenate()`**: Para concatenar arrays ao longo de um eixo específico, todos os arrays devem ter o mesmo número de dimensões. No caso, você está tentando concatenar ao longo do eixo `1` (`axis=1`), que requer que ambos os arrays tenham pelo menos 2 dimensões. No entanto, o `x2.T` ainda é 1D, causando o erro.

### Solução:
Se você deseja concatenar `x1` com `x2`, você precisa garantir que ambos os arrays tenham o mesmo número de dimensões. Uma solução é expandir a dimensão de `x2` para torná-lo 2D.


In [ ]:
x2 = x2[:, np.newaxis]  # Expande o array 1D para 2D, transformando-o em uma coluna
np.concatenate((x1, x2), axis=1)

### Explicação da Solução:
- **`x2[:, np.newaxis]`**: Isso transforma o array 1D `x2` em um array 2D com uma única coluna, compatível com o número de dimensões de `x1`. Agora ambos os arrays têm 2 dimensões, permitindo que `np.concatenate()` funcione sem erro.

Com essa mudança, o código deve funcionar corretamente sem gerar o erro de dimensões.

In [116]:
np.append(x1, x2.reshape(-1, 1), axis=1)

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [123]:
np.insert(x1, 0, x2.reshape(-1, 1).T, axis=1)

array([[ 1.  ,  1.67, 89.  ],
       [ 0.  ,  1.79, 85.  ],
       [ 1.  ,  1.69, 65.  ],
       [ 0.  ,  1.54, 57.  ],
       [ 1.  ,  1.5 , 45.  ]])

In [125]:
np.vstack([x1,x2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [129]:
x1

array([[ 1.67, 89.  ],
       [ 1.79, 85.  ],
       [ 1.69, 65.  ],
       [ 1.54, 57.  ],
       [ 1.5 , 45.  ]])

In [130]:
x2

array([[1],
       [0],
       [1],
       [0],
       [1]])

In [131]:
x1.T

array([[ 1.67,  1.79,  1.69,  1.54,  1.5 ],
       [89.  , 85.  , 65.  , 57.  , 45.  ]])

In [133]:
x2.T

array([[1, 0, 1, 0, 1]])

In [142]:
np.vstack([x1.T,x2.T])

array([[ 1.67,  1.79,  1.69,  1.54,  1.5 ],
       [89.  , 85.  , 65.  , 57.  , 45.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  1.  ]])

In [135]:
np.hstack([x1, x2.reshape(-1, 1)])

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [138]:
np.hstack([x1.T, x2.T])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [139]:
np.column_stack([x1, x2])

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ]])

In [141]:
np.row_stack([x1.T, x2.T])

array([[ 1.67,  1.79,  1.69,  1.54,  1.5 ],
       [89.  , 85.  , 65.  , 57.  , 45.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  1.  ]])

In [144]:
# Agora temos a tabela de dados abaixo.
table = np.array([[1.67, 89., 1],
                  [1.79, 85., 0],
                  [1.69, 65., 1],
                  [1.54, 57., 0],
                  [1.50, 45., 1]])

# Mas tinhamos esquecido de outras 3 pessoas!
new_table = np.array([[1.78, 91, 0],
                      [1.72, 67, 1],
                      [1.77, 76, 1]])

In [145]:
# Como podemos juntar as tabelas?
np.vstack([table, new_table])

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ],
       [ 1.78, 91.  ,  0.  ],
       [ 1.72, 67.  ,  1.  ],
       [ 1.77, 76.  ,  1.  ]])

In [146]:
np.concatenate((table, new_table), axis=0)

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ],
       [ 1.78, 91.  ,  0.  ],
       [ 1.72, 67.  ,  1.  ],
       [ 1.77, 76.  ,  1.  ]])

In [147]:
np.append(table, new_table, axis=0)

array([[ 1.67, 89.  ,  1.  ],
       [ 1.79, 85.  ,  0.  ],
       [ 1.69, 65.  ,  1.  ],
       [ 1.54, 57.  ,  0.  ],
       [ 1.5 , 45.  ,  1.  ],
       [ 1.78, 91.  ,  0.  ],
       [ 1.72, 67.  ,  1.  ],
       [ 1.77, 76.  ,  1.  ]])

Extra

In [148]:
# Inversão de matriz
A = np.array(
    [[6, 1, 1],
     [4, -2, 5],
     [2, 8, 7]]
)
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

# Operações Básicas

In [149]:
matriz

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [150]:
#Podemos multiplicar por um escalar
matriz_dobro = 2 * matriz
matriz_dobro

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.],
       [20., 22., 24.]])

In [151]:
# Podemos somar duas matrizes
print(matriz + matriz_dobro)

[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]
 [30. 33. 36.]]


In [152]:
# Multiplicação elemento por elemento
print(matriz * matriz_dobro)

[[  2.   8.  18.]
 [ 32.  50.  72.]
 [ 98. 128. 162.]
 [200. 242. 288.]]


In [153]:
print(matriz.shape)
print(matriz_dobro.shape)

(4, 3)
(4, 3)


In [154]:
matriz

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [161]:
matriz_dobro.T

array([[ 2.,  8., 14., 20.],
       [ 4., 10., 16., 22.],
       [ 6., 12., 18., 24.]])

In [159]:
# Produto matricial
print(matriz @ matriz_dobro.T)

[[ 28.  64. 100. 136.]
 [ 64. 154. 244. 334.]
 [100. 244. 388. 532.]
 [136. 334. 532. 730.]]


**Bora praticar!**  
  
Transforme os dados presentes no arquivo csv **dados_artificiais.csv**, que está na pasta **dados** em um numpy array (matriz). Apenas para facilitar o exercício, os dados do arquivo já se encontram na célula abaixo, mas aqui cabe ressaltar o motivo de estarmos utilizando o numpy para análise de dados.

In [3]:
lista_artificial =  [[1.78881069287776, 65.6481019432242, 0],
                    [1.5667844336950, 76.6427679834926, 0],
                    [2.0921930548074, 55.4681853258539, 1],
                    [1.7824709172724, 67.28199736248, 1],
                    [1.7357669765411, 69.2890076331505, 0],
                    [1.6869746476945, 56.8400511361321, 0],
                    [1.7971046329794, 65.2089732846482, 1],
                    [1.1873490549389, 48.1647639458379, 0],
                    [1.5958914364289, 45.4106481398706, 1],
                    [1.3962817760658, 67.9301133367375, 0],
                    [1.6061481645731, 67.7196040973561, 0],
                    [1.7075899674617, 45.6093326162225, 0],
                    [1.7355131159863, 64.8454515098479, 0],
                    [1.6720551819612, 39.7059515043444, 1],
                    [1.7233770692063, 50.0588802056305, 1],
                    [1.6845742723083, 56.5450873826135, 1],
                    [1.7332589297219, 37.5121875909276, 0],
                    [1.7578996592814, 57.3624223948134, 0],
                    [1.9133377051681, 69.3072463864561, 1],
                    [1.4560483434458, 69.3423371108747, 0]
]

dados_matriz = np.array(lista_artificial)
print(dados_matriz)

[[ 1.78881069 65.64810194  0.        ]
 [ 1.56678443 76.64276798  0.        ]
 [ 2.09219305 55.46818533  1.        ]
 [ 1.78247092 67.28199736  1.        ]
 [ 1.73576698 69.28900763  0.        ]
 [ 1.68697465 56.84005114  0.        ]
 [ 1.79710463 65.20897328  1.        ]
 [ 1.18734905 48.16476395  0.        ]
 [ 1.59589144 45.41064814  1.        ]
 [ 1.39628178 67.93011334  0.        ]
 [ 1.60614816 67.7196041   0.        ]
 [ 1.70758997 45.60933262  0.        ]
 [ 1.73551312 64.84545151  0.        ]
 [ 1.67205518 39.7059515   1.        ]
 [ 1.72337707 50.05888021  1.        ]
 [ 1.68457427 56.54508738  1.        ]
 [ 1.73325893 37.51218759  0.        ]
 [ 1.75789966 57.36242239  0.        ]
 [ 1.91333771 69.30724639  1.        ]
 [ 1.45604834 69.34233711  0.        ]]


Utilize esta matriz para calcular o IMC, utilizando a equação

```
IMC = peso / altura**2
```
e insira na nova tabela

In [12]:
imc_array = [(i[1] / i[0]**2) for i in dados_matriz]
imc_array_np = np.array([imc_array])
print(type(imc_array_np))
print(imc_array_np.shape)
print(imc_array_np)
matriz_imc = np.concatenate((lista_artificial, imc_array_np.T), axis = 1)
matriz_imc

<class 'numpy.ndarray'>
(1, 20)
[[20.51603397 31.22142239 12.67186232 21.17648965 22.99754611 19.97272618
  20.19113045 34.16430689 17.8299864  34.84305285 26.25083964 15.64179279
  21.52899308 14.20215982 16.85467995 19.92574427 12.48663736 18.56262192
  18.93195155 32.70746504]]


array([[ 1.78881069, 65.64810194,  0.        , 20.51603397],
       [ 1.56678443, 76.64276798,  0.        , 31.22142239],
       [ 2.09219305, 55.46818533,  1.        , 12.67186232],
       [ 1.78247092, 67.28199736,  1.        , 21.17648965],
       [ 1.73576698, 69.28900763,  0.        , 22.99754611],
       [ 1.68697465, 56.84005114,  0.        , 19.97272618],
       [ 1.79710463, 65.20897328,  1.        , 20.19113045],
       [ 1.18734905, 48.16476395,  0.        , 34.16430689],
       [ 1.59589144, 45.41064814,  1.        , 17.8299864 ],
       [ 1.39628178, 67.93011334,  0.        , 34.84305285],
       [ 1.60614816, 67.7196041 ,  0.        , 26.25083964],
       [ 1.70758997, 45.60933262,  0.        , 15.64179279],
       [ 1.73551312, 64.84545151,  0.        , 21.52899308],
       [ 1.67205518, 39.7059515 ,  1.        , 14.20215982],
       [ 1.72337707, 50.05888021,  1.        , 16.85467995],
       [ 1.68457427, 56.54508738,  1.        , 19.92574427],
       [ 1.73325893, 37.

In [13]:
IMC = [i[1] / i[0]**2 for i in dados_matriz]
IMC

[20.516033969644194,
 31.221422393286545,
 12.671862322378622,
 21.17648965106973,
 22.99754610962119,
 19.972726183561296,
 20.191130450290462,
 34.16430688742957,
 17.82998640186705,
 34.84305285178067,
 26.250839638369474,
 15.641792787462661,
 21.528993082184783,
 14.20215981997273,
 16.854679954620202,
 19.92574427273178,
 12.486637355204843,
 18.56262192376198,
 18.931951552368982,
 32.70746503885114]

In [23]:
dados_np = np.array(lista_artificial)
# print(dados_np)

altura = dados_np[:,0]
# print(altura)
peso = dados_np[:,1]
# print(peso)
imc = peso / altura**2

dados_imc_np = np.column_stack((dados_np, imc))

print(dados_imc_np)

[[ 1.78881069 65.64810194  0.         20.51603397]
 [ 1.56678443 76.64276798  0.         31.22142239]
 [ 2.09219305 55.46818533  1.         12.67186232]
 [ 1.78247092 67.28199736  1.         21.17648965]
 [ 1.73576698 69.28900763  0.         22.99754611]
 [ 1.68697465 56.84005114  0.         19.97272618]
 [ 1.79710463 65.20897328  1.         20.19113045]
 [ 1.18734905 48.16476395  0.         34.16430689]
 [ 1.59589144 45.41064814  1.         17.8299864 ]
 [ 1.39628178 67.93011334  0.         34.84305285]
 [ 1.60614816 67.7196041   0.         26.25083964]
 [ 1.70758997 45.60933262  0.         15.64179279]
 [ 1.73551312 64.84545151  0.         21.52899308]
 [ 1.67205518 39.7059515   1.         14.20215982]
 [ 1.72337707 50.05888021  1.         16.85467995]
 [ 1.68457427 56.54508738  1.         19.92574427]
 [ 1.73325893 37.51218759  0.         12.48663736]
 [ 1.75789966 57.36242239  0.         18.56262192]
 [ 1.91333771 69.30724639  1.         18.93195155]
 [ 1.45604834 69.34233711  0.  

In [24]:
# nara 
cols = dados_matriz[:, :3]

additional_col = dados_matriz[:, 1] / dados_matriz[:, 0] ** 2

new_array = np.column_stack((cols, additional_col))

for row in new_array:
    print(row)

[ 1.78881069 65.64810194  0.         20.51603397]
[ 1.56678443 76.64276798  0.         31.22142239]
[ 2.09219305 55.46818533  1.         12.67186232]
[ 1.78247092 67.28199736  1.         21.17648965]
[ 1.73576698 69.28900763  0.         22.99754611]
[ 1.68697465 56.84005114  0.         19.97272618]
[ 1.79710463 65.20897328  1.         20.19113045]
[ 1.18734905 48.16476395  0.         34.16430689]
[ 1.59589144 45.41064814  1.         17.8299864 ]
[ 1.39628178 67.93011334  0.         34.84305285]
[ 1.60614816 67.7196041   0.         26.25083964]
[ 1.70758997 45.60933262  0.         15.64179279]
[ 1.73551312 64.84545151  0.         21.52899308]
[ 1.67205518 39.7059515   1.         14.20215982]
[ 1.72337707 50.05888021  1.         16.85467995]
[ 1.68457427 56.54508738  1.         19.92574427]
[ 1.73325893 37.51218759  0.         12.48663736]
[ 1.75789966 57.36242239  0.         18.56262192]
[ 1.91333771 69.30724639  1.         18.93195155]
[ 1.45604834 69.34233711  0.         32.70746504]


In [ ]:
# felipe
imc = np.array(list(map(lambda dados: dados[1]/dados[0]**2, dados_matriz)))
dados_matriz2 = np.concatenate((dados_matriz, imc.reshape(-1,1)), axis=1)
dados_matriz2

| IMC             | Categoria           |   |
|-----------------|---------------------|---|
| abaixo de 16,00 | Baixo peso Grau III |   |
| 16,00 a 16,99   | Baixo peso Grau II  |   |
| 17,00 a 18.49   | Baixo peso Grau I   |   |
| 18,50 a 24,99   | Peso ideal          |   |
| 25,00 a 29,99   | Sobrepeso           |   |
| 30,00 a 34,99   | Obesidade Grau I    |   |
| 35,00 a 39,99   | Obesidade Grau II   |   |
| 40,0 e acima    | Obesidade Grau III  |   |

Agora utilize a tabela acima para indicar a qual categoria cada valor de IMC se enquadra. Insira novamente na tabela.

In [25]:
categorias_imc = []
for valor_imc in imc:
    if valor_imc < 16.00:
        categorias_imc.append("Baixo peso Grau III")
    elif 16.00 <= valor_imc <= 16.99:
        categorias_imc.append("Baixo peso Grau II")
    elif 17.00 <= valor_imc <= 18.49:
        categorias_imc.append("Baixo peso Grau I")
    elif 18.50 <= valor_imc <= 24.99:
        categorias_imc.append("Peso ideal")
    elif 25.00 <= valor_imc <= 29.99:
        categorias_imc.append("Sobrepeso")
    elif 30.00 <= valor_imc <= 34.99:
        categorias_imc.append("Obesidade Grau I")
    elif 35.00 <= valor_imc <= 39.99:
        categorias_imc.append("Obesidade Grau II")
    else:
        categorias_imc.append("Obesidade Grau III")

matriz_dados = np.column_stack((dados_matriz, categorias_imc))

print("Nova Tabela com IMC e Categoria:")
print(matriz_dados)

Nova Tabela com IMC e Categoria:
[['1.78881069287776' '65.6481019432242' '0.0' 'Peso ideal']
 ['1.566784433695' '76.6427679834926' '0.0' 'Obesidade Grau I']
 ['2.0921930548074' '55.4681853258539' '1.0' 'Baixo peso Grau III']
 ['1.7824709172724' '67.28199736248' '1.0' 'Peso ideal']
 ['1.7357669765411' '69.2890076331505' '0.0' 'Peso ideal']
 ['1.6869746476945' '56.8400511361321' '0.0' 'Peso ideal']
 ['1.7971046329794' '65.2089732846482' '1.0' 'Peso ideal']
 ['1.1873490549389' '48.1647639458379' '0.0' 'Obesidade Grau I']
 ['1.5958914364289' '45.4106481398706' '1.0' 'Baixo peso Grau I']
 ['1.3962817760658' '67.9301133367375' '0.0' 'Obesidade Grau I']
 ['1.6061481645731' '67.7196040973561' '0.0' 'Sobrepeso']
 ['1.7075899674617' '45.6093326162225' '0.0' 'Baixo peso Grau III']
 ['1.7355131159863' '64.8454515098479' '0.0' 'Peso ideal']
 ['1.6720551819612' '39.7059515043444' '1.0' 'Baixo peso Grau III']
 ['1.7233770692063' '50.0588802056305' '1.0' 'Baixo peso Grau II']
 ['1.6845742723083' '56.5

In [33]:
print(dados_imc_np[:, 3])

[20.51603397 31.22142239 12.67186232 21.17648965 22.99754611 19.97272618
 20.19113045 34.16430689 17.8299864  34.84305285 26.25083964 15.64179279
 21.52899308 14.20215982 16.85467995 19.92574427 12.48663736 18.56262192
 18.93195155 32.70746504]


In [32]:
categorias_IMC = np.array([
    "Baixo peso Grau III" if imc < 16.00
    else "Baixo peso Grau II" if 16.00 <= imc <= 16.99
    else "Baixo peso Grau I" if 17.00 <= imc <= 18.49
    else "Peso ideal" if 18.50 <= imc <= 24.99
    else "Sobrepeso" if 25.00 <= imc <= 29.99
    else "Obesidade Grau I" if 30.00 <= imc <= 34.99
    else "Obesidade Grau II" if 35.00 <= imc <= 39.99
    else "Obesidade Grau III"
    for imc in dados_imc_np[:, 3]
], dtype=object)
lista_artificial_com_categorias = np.column_stack((dados_imc_np, categorias_IMC))

print(lista_artificial_com_categorias)

[[1.78881069287776 65.6481019432242 0.0 20.516033969644194 'Peso ideal']
 [1.566784433695 76.6427679834926 0.0 31.221422393286545
  'Obesidade Grau I']
 [2.0921930548074 55.4681853258539 1.0 12.671862322378622
  'Baixo peso Grau III']
 [1.7824709172724 67.28199736248 1.0 21.17648965106973 'Peso ideal']
 [1.7357669765411 69.2890076331505 0.0 22.99754610962119 'Peso ideal']
 [1.6869746476945 56.8400511361321 0.0 19.972726183561296 'Peso ideal']
 [1.7971046329794 65.2089732846482 1.0 20.191130450290462 'Peso ideal']
 [1.1873490549389 48.1647639458379 0.0 34.16430688742957
  'Obesidade Grau I']
 [1.5958914364289 45.4106481398706 1.0 17.82998640186705
  'Baixo peso Grau I']
 [1.3962817760658 67.9301133367375 0.0 34.84305285178067
  'Obesidade Grau I']
 [1.6061481645731 67.7196040973561 0.0 26.250839638369474 'Sobrepeso']
 [1.7075899674617 45.6093326162225 0.0 15.641792787462661
  'Baixo peso Grau III']
 [1.7355131159863 64.8454515098479 0.0 21.528993082184783 'Peso ideal']
 [1.6720551819612

### Tipos de dados

Primeiro vamos falar do infinito (e além).

Quando fazemos operações de ponto flutuante no computador, existe um padrão técnico (definido pela IEEE, o Instituto de Engenheiros Eletro-eletrônicos) que define algumas coisas que uma biblioteca tem que ter.

Especificamente, aqui vamos falar de duas coisas:
- Not a Number (NAN)
- Infinito

In [162]:
# Not a Number é o resultado de operações inválidas.
# Embora ele exista no Python, operações inválidas tendem a levantar um erro.
0/0

ZeroDivisionError: division by zero

In [165]:
# Para usá-lo no python, temos que converter string para float.
float('NaN')

nan

In [164]:
int('NaN')

ValueError: invalid literal for int() with base 10: 'NaN'

In [166]:
# No numpy, temos o objeto nan.
print(np.nan)
print(type(np.nan))

nan
<class 'float'>


In [167]:
# Já no numpy, operações inválidas retornam NaN mesmo.
x1 = np.array([1, 0, 1, 0])
x2 = np.array([2, 1, 2, 0])

print(x1/x2)

[0.5 0.  0.5 nan]


C:\Users\costa\AppData\Local\Temp\ipykernel_32880\2566010472.py:5: RuntimeWarning: invalid value encountered in divide
  print(x1/x2)


In [168]:
# "Infinito", no padrão, pode ser pensado como um número que é maior que qualquer outro número.
# No caso de "-infinito", temos um número que é menor que qualquer outro número.
1/0

ZeroDivisionError: division by zero

In [169]:
print(float('inf'))
print(float('inf') > 10000000000000000000000000000)
print(-float('inf') < -10000000000000000000000000000)

inf
True
True


In [170]:
# No Numpy, não seria diferente.
print(np.inf)
print(np.inf > 10000000000000000000000000000)
print(-np.inf < -10000000000000000000000000000)
print(type(np.inf))

inf
True
True
<class 'float'>


In [176]:
# No numpy, algumas operações podem gerar infinitos. 1 / 0 = 
x1 = np.array([1, 0, 2, 1, 0])
x2 = np.array([2, 1, np.inf, 2, 0])

print(type(x1.[0]2.3))
print(x2/x1)

<class 'float'>
<class 'float'>
[ 2. inf inf  2. nan]


C:\Users\costa\AppData\Local\Temp\ipykernel_32880\2531579327.py:6: RuntimeWarning: divide by zero encountered in divide
  print(x2/x1)
C:\Users\costa\AppData\Local\Temp\ipykernel_32880\2531579327.py:6: RuntimeWarning: invalid value encountered in divide
  print(x2/x1)


In [178]:
print(type(np.array([2.3][0][0])))

TypeError: 'float' object is not subscriptable

Notou que tanto infinito quanto NaN são do tipo "float"? Não são float64, nem float32, nem nada assim.

Isso é devido à hierarquia de dtypes do numpy.

![hierarchy](https://numpy.org/doc/stable/_images/dtype-hierarchy.png)

## Mini tarefa

Utilizando numpy crie duas matrizes com 5 linhas e 4 colunas, sendo uma delas apenas contendo números 1 e a segunda uma matriz olho (eye). Após isso, some as duas matrizes.

In [41]:
# matriz_1 = [[1, 1, 1, 1]
#             [1, 1, 1, 1]
#             [1, 1, 1, 1]
#             [1, 1, 1, 1]
#             [1, 1, 1, 1]]

# matriz_eye= [[1, 0, 0, 0]
#             [0, 1, 0, 0]
#             [0, 0, 1, 0]
#             [0, 0, 0, 1]
#             [0, 0, 0, 0]]

matriz_ones = np.ones((5, 4))
matriz_eye = np.eye(5,4)
matriz_resultado = matriz_eye + matriz_ones
matriz_resultado

array([[2., 1., 1., 1.],
       [1., 2., 1., 1.],
       [1., 1., 2., 1.],
       [1., 1., 1., 2.],
       [1., 1., 1., 1.]])